version: 2.1
jobs:
  build_all:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run:
          name: test
          command: echo "test"

  build:
    docker:
      - image: circleci/node:14
        environment:
          CI: true
          REACT_APP_SERVER_URL: http://react-app:3000

    steps:
      - checkout
      - setup_remote_docker

      #Clone the Playwright tests repository to a different directory within the workspace
      - run:
          name: Clone Playwright tests repository
          command: git clone https://github.com/MohamedEssam4444/docker-compose-QA-testing.git

      - run:
          name: Run React app
          command: |
            docker build . -t react-app
            docker run -p 3000:3000 --name react-app react-app
            sleep 100
            docker ps
            curl http://react-app:3000

      # Use Docker-Compose to run both services together
      - run:
          name: Run React app and Playwright tests
          command: |
            cd docker-compose-QA-testing
            docker-compose up -d
            sleep 100
            docker ps
            curl http://react-app:3000
            npm uninstall playwright
            npm install -D @playwright/test
            npx playwright install
            sleep 60
            curl http://localhost:3000
            npx playwright test

      # Clean up containers after the tests complete
      - run:
          name: Cleanup
          command: |
            docker-compose down

# Define workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_all

      - build:
          filters:
            branches:
              only:
                - dev
                - stage
                - master
                - main