version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
        environment:
          - CI: true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build React app Docker image
          command: docker build -t react-app:latest .
      - run:
          name: Run React app container
          command: docker run -d -p 3000:3000 --name react-app-container react-app:latest
      - run:
          name: Run React app tests
          command: npm test
      - run:
          name: Cleanup
          command: docker stop react-app-container && docker rm react-app-container

workflows:
  version: 2
  build_and_test:
    jobs:
      - build