version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
        environment:
          CI: true
    steps:
      - checkout
      - setup_remote_docker

      # Use Docker-Compose to run both services together
      - run:
          name: Run React app and Playwright tests
          command: |
            docker-compose up

      - run: 
          name: run your tests buddy
          command: |
            echo "please your your tests in this stage"
            docker ps

      # Clean up containers after the tests complete
      - run:
          name: Cleanup
          command: |
            docker compose down

# Define workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
