version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
        environment:
          CI: true
          REACT_APP_SERVER_URL: http://react-app:3000

    steps:
      - checkout
      - setup_remote_docker
      # - run: 
      #     name: clone playwright repo
      #     command: git clone https://github.com/microsoft/playwright.git
      # Build the React app Docker image

      # - run:
      #     name: Build React app Docker image
      #     command: docker build -t react-app:latest .

      # # Start the React app container
      # - run:
      #     name: Run React app
      #     command: docker run -d -p 3000:3000 --name react-app-container react-app:latest

      # Wait for the React app to start (Adjust sleep time as needed)
      # - run:
      #     name: Wait for React app to start
      #     command: sleep 10

      #Clone the Playwright tests repository to a different directory within the workspace
      # - run:
      #     name: Clone Playwright tests repository
      #     command: git clone https://github.com/MohamedEssam4444/docker-compose-QA-testing.git

      # # Build the Playwright tests Docker image
      # - run:
      #     name: Build Playwright tests Docker image
      #     command: docker build -t playwright-tests playwright-tests

      # Use Docker-Compose to run both services together
      - run:
          name: Run React app and Playwright tests
          command: |
            cd docker-compose-QA-testing
            docker-compose up -d

      - run:
          name: run npx pw tests
          command: |
            echo ${REACT_APP_SERVER_URL}
            npx playwright test


      # Clean up containers after the tests complete
      - run:
          name: Cleanup
          command: |
            docker compose down

# Define workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
