version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
        environment:
          - CI: true
    steps:
      - checkout
      - setup_remote_docker

      # Build the React app Docker image
      - run:
          name: Build React app Docker image
          command: docker build -t react-app:latest .

      # Use Docker-Compose to run both services together
      - run:
          name: Run React app and Playwright tests
          command: |
            docker-compose -f ../pw_repo/docker-compose.yml up --abort-on-container-exit

      - run:
          name: Cleanup
          command: docker-compose -f ../pw_repo/docker-compose.yml down

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
