version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
        environment:
          CI: true
          REACT_APP_SERVER_URL: http://react-app:3000

    steps:
      - checkout
      - setup_remote_docker

      #Clone the Playwright tests repository to a different directory within the workspace
      - run:
          name: Clone Playwright tests repository
          command: git clone https://github.com/MohamedEssam4444/docker-compose-QA-testing.git

      # Use Docker-Compose to run both services together
      - run:
          name: Run React app and Playwright tests
          command: |
            cd docker-compose-QA-testing
            docker-compose up -d

      - run:
          name: install playwright
          command: |
            cd docker-compose-QA-testing
            npm uninstall playwright
            npm install -D @playwright/test
            npx playwright install

      - run:
          name: run npx pw tests
          command: |
            cd docker-compose-QA-testing
            echo ${REACT_APP_SERVER_URL}
            npx playwright test


      # Clean up containers after the tests complete
      - run:
          name: Cleanup
          command: |
            docker-compose down

# Define workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
